
import java.awt.Font;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S219
 */
public class ihm_3 extends javax.swing.JFrame {

    private int etat;
    Font bold,plain;
    public ihm_3() {
        initComponents();
        this.initialiser();
    }
    
    private void initialiser() {
       etat = 1;
       bold = new Font(jButton1.getFont().getName(),Font.BOLD, jButton1.getFont().getSize());
       plain = new Font(jButton1.getFont().getName(),Font.PLAIN, jButton1.getFont().getSize());
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(false);
       jButton4.setEnabled(false);
       jButton1.setFont(plain);
       jButton2.setFont(plain);
       jButton3.setFont(plain);
       jButton4.setFont(plain);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setLabel("Bouton 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Bouton 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Bouton 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Bouton 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        switch(etat) {
            case 1 :
                etat = 2;
                jButton1.setFont(bold);
                break;
            case 2 :
                etat = 2;
                break;
            case 3 :
                break;
            case 4 :
                break;
            case 5 :
                jButton3.setEnabled(true);
                jButton4.setEnabled(true);
                jButton2.setEnabled(false);
                jButton1.setEnabled(false);
                jButton1.setFont(plain);
                jButton2.setFont(plain);
                etat = 3;
                break;
            case 6 :
                break;
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         switch(etat) {
            case 1 :
                etat = 5;
                jButton2.setFont(bold);
                break;
            case 2 :
                jButton3.setEnabled(true);
                jButton4.setEnabled(true);
                jButton2.setEnabled(false);
                jButton1.setEnabled(false);
                jButton1.setFont(plain);
                jButton2.setFont(plain);
                etat = 3;
                break;
            case 3 :
                break;
            case 4 :
                break;
            case 5 :
                etat = 5;
                break;
            case 6 :
                break;
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         switch(etat) {
            case 1 :
                break;
            case 2 :
                break;
            case 3 :
                etat = 4;
                jButton3.setFont(bold);
                break;
            case 4 :
                etat = 4;
                break;
            case 5 :
                break;
            case 6 :
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
                jButton2.setEnabled(true);
                jButton1.setEnabled(true);
                jButton3.setFont(plain);
                jButton4.setFont(plain);
                etat = 1;
                break;
        }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            switch(etat) {
            case 1 :
                break;
            case 2 :
                break;
            case 3 :
                etat = 6;
                jButton4.setFont(bold);
                break;
            case 4 :
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
                jButton2.setEnabled(true);
                jButton1.setEnabled(true);
                jButton3.setFont(plain);
                jButton4.setFont(plain);
                etat = 1;
                break;
            case 5 :
                break;
            case 6 :
                etat = 6;
                jButton4.setFont(bold);
                break;
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ihm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ihm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ihm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ihm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ihm_3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration                   

    
}
